config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :cars do
    collection do
      get 'upload'
      post 'upload_csv'
      get 'download_csv_template'
    end
  end
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "home#index"
  devise_for :users
  resources :bookings
  get 'admin/dashboard', to: 'admin#dashboard', as: 'admin_dashboard'
  post 'admin/send_csv', to: 'admin#send_csv', as: 'send_csv_admin_dashboard'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)
  
    respond_to do |format|
      if @review.save
        flash[:notice] = "Review was successfully created."
        format.html { redirect_to bookings_path }
        format.json { render :show, status: :created, location: @review }
      else
        flash[:alert] = "Failed to create review."
        format.html { redirect_to bookings_path, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy!

    respond_to do |format|
      format.html { redirect_to reviews_path, status: :see_other, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.permit(:response, :booking_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: review, class: "contents") do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul class="list-disc ml-6">
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :response %>
    <%= form.text_field :response, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": review.errors[:response].none?, "border-red-400 focus:outline-red-600": review.errors[:response].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :booking_id %>
    <%= form.text_field :booking_id, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": review.errors[:booking_id].none?, "border-red-400 focus:outline-red-600": review.errors[:booking_id].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/reviews/_review.html.erb
<div id="<%= dom_id review %>" class="my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Response:</strong>
    <%= review.response %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Booking:</strong>
    <%= review.booking_id %>
  </div>
</div>

app/views/reviews/edit.html.erb
<% content_for :title, "Editing review" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing review</h1>

  <%= render "form", review: @review %>

  <%= link_to "Show this review", @review, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to reviews", reviews_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/reviews/index.html.erb
<% content_for :title, "Reviews" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Reviews</h1>
    <%= link_to "New review", new_review_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="reviews" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @reviews.any? %>
      <% @reviews.each do |review| %>
        <div class="flex justify-between items-center">
          <%= render review %>
          <div class="space-x-2">
            <%= link_to "Show", review, class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_review_path(review), class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <div class="inline-block">
              <%= button_to "Destroy", review, method: :delete, class: "rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No reviews found.</p>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<% content_for :title, "New review" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New review</h1>

  <%= render "form", review: @review %>

  <%= link_to "Back to reviews", reviews_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/reviews/show.html.erb
<% content_for :title, "Showing review" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing review</h1>

  <%= render @review %>

  <%= link_to "Edit this review", edit_review_path(@review), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to reviews", reviews_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this review", @review, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>